/** A document using every format the editor offers. */
export const KITCHEN_SINK = [
  { insert: 'Title' }, { insert: '\n', attributes: { header: 1 } },
  { insert: 'Sub' }, { insert: '\n', attributes: { header: 2 } },
  { insert: 'Bold', attributes: { bold: true } }, { insert: ' ' },
  { insert: 'italic', attributes: { italic: true } }, { insert: ' ' },
  { insert: 'under', attributes: { underline: true } }, { insert: ' ' },
  { insert: 'strike', attributes: { strike: true } }, { insert: ' H' },
  { insert: '2', attributes: { script: 'sub' } }, { insert: 'O x' },
  { insert: '2', attributes: { script: 'super' } }, { insert: '\n', attributes: { align: 'center' } },
  { insert: 'Red', attributes: { color: 'rgb(230, 0, 0)' } }, { insert: ' ' },
  { insert: 'marked', attributes: { background: '#ffff00' } }, { insert: ' ' },
  { insert: 'big', attributes: { size: '24px' } }, { insert: ' ' },
  { insert: 'serif', attributes: { font: 'georgia' } }, { insert: ' ' },
  { insert: 'link', attributes: { link: 'https://example.com/?a=1&b=2' } }, { insert: '\n', attributes: { align: 'justify' } },
  { insert: 'One' }, { insert: '\n', attributes: { list: 'bullet' } },
  { insert: 'Nested' }, { insert: '\n', attributes: { list: 'bullet', indent: 1 } },
  { insert: 'Two' }, { insert: '\n', attributes: { list: 'bullet' } },
  { insert: 'First' }, { insert: '\n', attributes: { list: 'ordered' } },
  { insert: 'Sub a' }, { insert: '\n', attributes: { list: 'ordered', indent: 1 } },
  { insert: 'Quoted' }, { insert: '\n', attributes: { blockquote: true } },
  { insert: { divider: true } },
  { insert: 'Indented' }, { insert: '\n', attributes: { indent: 2 } },
  { insert: { image: 'https://images.example.com/logo.png' }, attributes: { width: '1200', alt: 'Logo "A"' } },
  { insert: '\n' },
  { insert: '\n' },
  { insert: 'End\n' },
];
